name: Run Takeout Cash Test (Windows)

on:
  workflow_dispatch  # Allows manual trigger from GitHub UI

jobs:
  run-test:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r Automation-logic/requirements.txt

      - name: Install Node.js & Appium
        run: |
          npm install -g appium
          appium -v  # Verify installation

      - name: Verify Running Emulator
        run: adb devices  # Check if the emulator is detected

      - name: Start Appium Server
        run: |
          Start-Process -NoNewWindow -FilePath "appium" -ArgumentList "--address 127.0.0.1 --port 4723"
          Start-Sleep -s 10  # Wait for Appium to start

      - name: Run Takeout Cash Test
        run: pytest Automation-logic/suits/test_orderflows/test_cash/test_takeout_cash.py --capture=no
