name: Run Takeout Cash Test

on: 
  workflow_dispatch  # Allows manual trigger from GitHub UI

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install Appium & Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt install -y nodejs
          npm install -g appium
          appium -v  # Verify installation

      - name: Run Takeout Cash Test
        run: pytest Automation-logic/suits/test_orderflows/test_cash/test_takeout_cash.py --capture=no
